### PR TITLE
Update install section

### PR DESCRIPTION
**Pull request by unixorn**
* Add antigen instructions
* Add zgen instructions
* Typo fix
* Minor reformatting of instructions section

### CODE REVIEW

**Comment by sfabrizio** [comment]
oh okey.. good stuff.. I wasn't sure If this will work also with antigen.. Thanks

**Comment by unixorn** [comment]
If it works with OMZ, it should work with Antigen and Zgen

**Comment by sfabrizio** [comment]
Nice.. I'll try them.. They are doing a lot easier the installing proccess

**Comment by unixorn** [comment]
They're both good. I use zgen because it starts new shell sessions faster.

**Pull request merged**
